# Generated by Django 6.1 on 2026-08-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.IntegerField(blank=True)),
                ('roll_no', models.IntegerField()),
                ('address', models.TextField()),
                ('course', models.CharField(choices=[('PFS', 'Python Full Stack'), ('JFS', 'Java Full Stack'), ('MERN', 'MERN Stack')], max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
